/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DealInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "accept" | "allowCancelUnacceptedAfter" | "allowCancelUnpaidAfter" | "assignMediator" | "cancel" | "dispute" | "feedback" | "feedbackForOwner" | "feedbackForTaker" | "fiatAmount" | "fund" | "getRoleAdmin" | "grantRole" | "hasRole" | "message" | "offer" | "paid" | "paymentInstructions" | "release" | "renounceRole" | "revokeRole" | "state" | "supportsInterface" | "taker" | "terms" | "tokenAmount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DealState" | "FeedbackGiven" | "Message" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'accept', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowCancelUnacceptedAfter', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowCancelUnpaidAfter', values?: undefined): string;
encodeFunctionData(functionFragment: 'assignMediator', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancel', values?: undefined): string;
encodeFunctionData(functionFragment: 'dispute', values?: undefined): string;
encodeFunctionData(functionFragment: 'feedback', values: [boolean, string]): string;
encodeFunctionData(functionFragment: 'feedbackForOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'feedbackForTaker', values?: undefined): string;
encodeFunctionData(functionFragment: 'fiatAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'fund', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'message', values: [string]): string;
encodeFunctionData(functionFragment: 'offer', values?: undefined): string;
encodeFunctionData(functionFragment: 'paid', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentInstructions', values?: undefined): string;
encodeFunctionData(functionFragment: 'release', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'taker', values?: undefined): string;
encodeFunctionData(functionFragment: 'terms', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenAmount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accept', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowCancelUnacceptedAfter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowCancelUnpaidAfter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignMediator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feedback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feedbackForOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feedbackForTaker', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fiatAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'message', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'offer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentInstructions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taker', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenAmount', data: BytesLike): Result;
  }

  
    export namespace DealStateEvent {
      export type InputTuple = [state: BigNumberish, sender: AddressLike];
      export type OutputTuple = [state: bigint, sender: string];
      export interface OutputObject {state: bigint, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeedbackGivenEvent {
      export type InputTuple = [to: AddressLike, upvote: boolean, message: string];
      export type OutputTuple = [to: string, upvote: boolean, message: string];
      export interface OutputObject {to: string, upvote: boolean, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MessageEvent {
      export type InputTuple = [sender: AddressLike, message: string];
      export type OutputTuple = [sender: string, message: string];
      export interface OutputObject {sender: string, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Deal extends BaseContract {
    
    connect(runner?: ContractRunner | null): Deal;
    waitForDeployment(): Promise<this>;

    interface: DealInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    accept: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allowCancelUnacceptedAfter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowCancelUnpaidAfter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    assignMediator: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    cancel: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    dispute: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    feedback: TypedContractMethod<
      [upvote: boolean, message_: string, ],
      [void],
      'nonpayable'
    >
    

    
    feedbackForOwner: TypedContractMethod<
      [],
      [[boolean, boolean, string] & {given: boolean, upvote: boolean, message: string }],
      'view'
    >
    

    
    feedbackForTaker: TypedContractMethod<
      [],
      [[boolean, boolean, string] & {given: boolean, upvote: boolean, message: string }],
      'view'
    >
    

    
    fiatAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    message: TypedContractMethod<
      [message_: string, ],
      [void],
      'nonpayable'
    >
    

    
    offer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paid: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paymentInstructions: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    release: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    taker: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    terms: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'accept'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowCancelUnacceptedAfter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowCancelUnpaidAfter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'assignMediator'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'dispute'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feedback'): TypedContractMethod<
      [upvote: boolean, message_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feedbackForOwner'): TypedContractMethod<
      [],
      [[boolean, boolean, string] & {given: boolean, upvote: boolean, message: string }],
      'view'
    >;
getFunction(nameOrSignature: 'feedbackForTaker'): TypedContractMethod<
      [],
      [[boolean, boolean, string] & {given: boolean, upvote: boolean, message: string }],
      'view'
    >;
getFunction(nameOrSignature: 'fiatAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'message'): TypedContractMethod<
      [message_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'offer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paid'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paymentInstructions'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'taker'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'terms'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'DealState'): TypedContractEvent<DealStateEvent.InputTuple, DealStateEvent.OutputTuple, DealStateEvent.OutputObject>;
getEvent(key: 'FeedbackGiven'): TypedContractEvent<FeedbackGivenEvent.InputTuple, FeedbackGivenEvent.OutputTuple, FeedbackGivenEvent.OutputObject>;
getEvent(key: 'Message'): TypedContractEvent<MessageEvent.InputTuple, MessageEvent.OutputTuple, MessageEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'DealState(uint8,address)': TypedContractEvent<DealStateEvent.InputTuple, DealStateEvent.OutputTuple, DealStateEvent.OutputObject>;
      DealState: TypedContractEvent<DealStateEvent.InputTuple, DealStateEvent.OutputTuple, DealStateEvent.OutputObject>;
    

      'FeedbackGiven(address,bool,string)': TypedContractEvent<FeedbackGivenEvent.InputTuple, FeedbackGivenEvent.OutputTuple, FeedbackGivenEvent.OutputObject>;
      FeedbackGiven: TypedContractEvent<FeedbackGivenEvent.InputTuple, FeedbackGivenEvent.OutputTuple, FeedbackGivenEvent.OutputObject>;
    

      'Message(address,string)': TypedContractEvent<MessageEvent.InputTuple, MessageEvent.OutputTuple, MessageEvent.OutputObject>;
      Message: TypedContractEvent<MessageEvent.InputTuple, MessageEvent.OutputTuple, MessageEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }