/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Deal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Deal__factory>
getContractFactory(name: 'DealFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DealFactory__factory>
getContractFactory(name: 'Market', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Market__factory>
getContractFactory(name: 'Offer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Offer__factory>
getContractFactory(name: 'OfferFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OfferFactory__factory>
getContractFactory(name: 'PriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PriceFeed__factory>
getContractFactory(name: 'RepToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RepToken__factory>
getContractFactory(name: 'IChainlink', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IChainlink__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockUniswapV3Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniswapV3Factory__factory>
getContractFactory(name: 'PoolBTC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolBTC__factory>
getContractFactory(name: 'PoolETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolETH__factory>

  getContractAt(name: 'Deal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Deal>
getContractAt(name: 'DealFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DealFactory>
getContractAt(name: 'Market', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Market>
getContractAt(name: 'Offer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Offer>
getContractAt(name: 'OfferFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OfferFactory>
getContractAt(name: 'PriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PriceFeed>
getContractAt(name: 'RepToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RepToken>
getContractAt(name: 'IChainlink', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IChainlink>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockUniswapV3Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniswapV3Factory>
getContractAt(name: 'PoolBTC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolBTC>
getContractAt(name: 'PoolETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolETH>

  deployContract(name: 'Deal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Deal>
deployContract(name: 'DealFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DealFactory>
deployContract(name: 'Market', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Market>
deployContract(name: 'Offer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Offer>
deployContract(name: 'OfferFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OfferFactory>
deployContract(name: 'PriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceFeed>
deployContract(name: 'RepToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RepToken>
deployContract(name: 'IChainlink', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IChainlink>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockUniswapV3Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Factory>
deployContract(name: 'PoolBTC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolBTC>
deployContract(name: 'PoolETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolETH>

  deployContract(name: 'Deal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Deal>
deployContract(name: 'DealFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DealFactory>
deployContract(name: 'Market', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Market>
deployContract(name: 'Offer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Offer>
deployContract(name: 'OfferFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OfferFactory>
deployContract(name: 'PriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceFeed>
deployContract(name: 'RepToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RepToken>
deployContract(name: 'IChainlink', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IChainlink>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockUniswapV3Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Factory>
deployContract(name: 'PoolBTC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolBTC>
deployContract(name: 'PoolETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolETH>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  