/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Fiats {
      
    export type FiatStruct = {symbol: string, toUSD: AddressLike}

    export type FiatStructOutput = [symbol: string, toUSD: string] & {symbol: string, toUSD: string }
  
    }

export declare namespace Methods {
      
    export type MethodStruct = {name: string, group: BigNumberish}

    export type MethodStructOutput = [name: string, group: bigint] & {name: string, group: bigint }
  
    }

export declare namespace Tokens {
      
    export type TokenStruct = {api: AddressLike, symbol: string, name: string, decimals: BigNumberish, uniswapPoolFee: BigNumberish}

    export type TokenStructOutput = [api: string, symbol: string, name: string, decimals: bigint, uniswapPoolFee: bigint] & {api: string, symbol: string, name: string, decimals: bigint, uniswapPoolFee: bigint }
  
    }

  export interface MarketInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "addDeal" | "addFiats" | "addMethods" | "addOffer" | "addTokens" | "convert" | "dealFactory" | "fiat" | "fundDeal" | "getFiats" | "getMethods" | "getOffers" | "getPrice" | "getTokens" | "hasOffer" | "initialize" | "mediator" | "method" | "offerFactory" | "owner" | "proxiableUUID" | "removeFiats" | "removeMethods" | "removeTokens" | "renounceOwnership" | "repToken" | "setDealFactory" | "setMediator" | "setOfferFactory" | "token" | "transferOwnership" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DealCreated" | "Initialized" | "OfferCreated" | "OwnershipTransferred" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addDeal', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addFiats', values: [Fiats.FiatStruct[]]): string;
encodeFunctionData(functionFragment: 'addMethods', values: [Methods.MethodStruct[]]): string;
encodeFunctionData(functionFragment: 'addOffer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addTokens', values: [AddressLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'convert', values: [BigNumberish, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'dealFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'fiat', values: [string]): string;
encodeFunctionData(functionFragment: 'fundDeal', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFiats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMethods', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOffers', values: [boolean, string, string, string]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasOffer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mediator', values?: undefined): string;
encodeFunctionData(functionFragment: 'method', values: [string]): string;
encodeFunctionData(functionFragment: 'offerFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeFiats', values: [string[]]): string;
encodeFunctionData(functionFragment: 'removeMethods', values: [string[]]): string;
encodeFunctionData(functionFragment: 'removeTokens', values: [string[]]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDealFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMediator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOfferFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'token', values: [string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addFiats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addMethods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dealFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fiat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFiats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMethods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOffers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mediator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'method', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'offerFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFiats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeMethods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDealFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMediator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOfferFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace DealCreatedEvent {
      export type InputTuple = [offerOwner: AddressLike, taker: AddressLike, offer: AddressLike, deal: AddressLike];
      export type OutputTuple = [offerOwner: string, taker: string, offer: string, deal: string];
      export interface OutputObject {offerOwner: string, taker: string, offer: string, deal: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfferCreatedEvent {
      export type InputTuple = [owner: AddressLike, token: string, fiat: string, offer: AddressLike];
      export type OutputTuple = [owner: string, token: string, fiat: string, offer: string];
      export interface OutputObject {owner: string, token: string, fiat: string, offer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Market extends BaseContract {
    
    connect(runner?: ContractRunner | null): Market;
    waitForDeployment(): Promise<this>;

    interface: MarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addDeal: TypedContractMethod<
      [deal: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addFiats: TypedContractMethod<
      [fiats_: Fiats.FiatStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    addMethods: TypedContractMethod<
      [new_: Methods.MethodStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    addOffer: TypedContractMethod<
      [offer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addTokens: TypedContractMethod<
      [tokens_: AddressLike[], uniswapPoolFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    convert: TypedContractMethod<
      [amount_: BigNumberish, fromFiat_: string, toToken_: string, denominator: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    dealFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fiat: TypedContractMethod<
      [symbol_: string, ],
      [Fiats.FiatStructOutput],
      'view'
    >
    

    
    fundDeal: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getFiats: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getMethods: TypedContractMethod<
      [],
      [Methods.MethodStructOutput[]],
      'view'
    >
    

    
    getOffers: TypedContractMethod<
      [isSell_: boolean, token_: string, fiat_: string, method_: string, ],
      [string[]],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [token_: string, fiat_: string, ],
      [bigint],
      'view'
    >
    

    
    getTokens: TypedContractMethod<
      [],
      [Tokens.TokenStructOutput[]],
      'view'
    >
    

    
    hasOffer: TypedContractMethod<
      [offer_: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [offerFactory_: AddressLike, dealFactory_: AddressLike, repToken_: AddressLike, uniswap_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    mediator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    method: TypedContractMethod<
      [symbol_: string, ],
      [Methods.MethodStructOutput],
      'view'
    >
    

    
    offerFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeFiats: TypedContractMethod<
      [fiat_: string[], ],
      [void],
      'nonpayable'
    >
    

    
    removeMethods: TypedContractMethod<
      [names_: string[], ],
      [void],
      'nonpayable'
    >
    

    
    removeTokens: TypedContractMethod<
      [token_: string[], ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setDealFactory: TypedContractMethod<
      [dealFactory_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMediator: TypedContractMethod<
      [mediator_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setOfferFactory: TypedContractMethod<
      [offerFactory_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [symbol_: string, ],
      [Tokens.TokenStructOutput],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addDeal'): TypedContractMethod<
      [deal: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addFiats'): TypedContractMethod<
      [fiats_: Fiats.FiatStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addMethods'): TypedContractMethod<
      [new_: Methods.MethodStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addOffer'): TypedContractMethod<
      [offer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addTokens'): TypedContractMethod<
      [tokens_: AddressLike[], uniswapPoolFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'convert'): TypedContractMethod<
      [amount_: BigNumberish, fromFiat_: string, toToken_: string, denominator: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dealFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fiat'): TypedContractMethod<
      [symbol_: string, ],
      [Fiats.FiatStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'fundDeal'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getFiats'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMethods'): TypedContractMethod<
      [],
      [Methods.MethodStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOffers'): TypedContractMethod<
      [isSell_: boolean, token_: string, fiat_: string, method_: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [token_: string, fiat_: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTokens'): TypedContractMethod<
      [],
      [Tokens.TokenStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasOffer'): TypedContractMethod<
      [offer_: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [offerFactory_: AddressLike, dealFactory_: AddressLike, repToken_: AddressLike, uniswap_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mediator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'method'): TypedContractMethod<
      [symbol_: string, ],
      [Methods.MethodStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'offerFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeFiats'): TypedContractMethod<
      [fiat_: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeMethods'): TypedContractMethod<
      [names_: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeTokens'): TypedContractMethod<
      [token_: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setDealFactory'): TypedContractMethod<
      [dealFactory_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMediator'): TypedContractMethod<
      [mediator_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOfferFactory'): TypedContractMethod<
      [offerFactory_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [symbol_: string, ],
      [Tokens.TokenStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'DealCreated'): TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OfferCreated'): TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'DealCreated(address,address,address,address)': TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
      DealCreated: TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OfferCreated(address,string,string,address)': TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
      OfferCreated: TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }