/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Offer {
      
    export type LimitsStruct = {min: BigNumberish, max: BigNumberish}

    export type LimitsStructOutput = [min: bigint, max: bigint] & {min: bigint, max: bigint }
  
    }

  export interface OfferInterface extends Interface {
    getFunction(nameOrSignature: "disabled" | "fiat" | "isSell" | "limits" | "method" | "owner" | "rate" | "setDisabled" | "setLimits" | "setRate" | "setTerms" | "terms" | "token"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OfferUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'disabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'fiat', values?: undefined): string;
encodeFunctionData(functionFragment: 'isSell', values?: undefined): string;
encodeFunctionData(functionFragment: 'limits', values?: undefined): string;
encodeFunctionData(functionFragment: 'method', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'rate', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDisabled', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setLimits', values: [Offer.LimitsStruct]): string;
encodeFunctionData(functionFragment: 'setRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTerms', values: [string]): string;
encodeFunctionData(functionFragment: 'terms', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'disabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fiat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'limits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'method', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDisabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTerms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  }

  
    export namespace OfferUpdatedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Offer extends BaseContract {
    
    connect(runner?: ContractRunner | null): Offer;
    waitForDeployment(): Promise<this>;

    interface: OfferInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    disabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    fiat: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isSell: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    limits: TypedContractMethod<
      [],
      [[bigint, bigint] & {min: bigint, max: bigint }],
      'view'
    >
    

    
    method: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setDisabled: TypedContractMethod<
      [disabled_: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setLimits: TypedContractMethod<
      [limits_: Offer.LimitsStruct, ],
      [void],
      'nonpayable'
    >
    

    
    setRate: TypedContractMethod<
      [rate_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTerms: TypedContractMethod<
      [terms_: string, ],
      [void],
      'nonpayable'
    >
    

    
    terms: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'disabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'fiat'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isSell'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'limits'): TypedContractMethod<
      [],
      [[bigint, bigint] & {min: bigint, max: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'method'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setDisabled'): TypedContractMethod<
      [disabled_: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLimits'): TypedContractMethod<
      [limits_: Offer.LimitsStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRate'): TypedContractMethod<
      [rate_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTerms'): TypedContractMethod<
      [terms_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'terms'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'OfferUpdated'): TypedContractEvent<OfferUpdatedEvent.InputTuple, OfferUpdatedEvent.OutputTuple, OfferUpdatedEvent.OutputObject>;

    filters: {
      
      'OfferUpdated()': TypedContractEvent<OfferUpdatedEvent.InputTuple, OfferUpdatedEvent.OutputTuple, OfferUpdatedEvent.OutputObject>;
      OfferUpdated: TypedContractEvent<OfferUpdatedEvent.InputTuple, OfferUpdatedEvent.OutputTuple, OfferUpdatedEvent.OutputObject>;
    
    };
  }