// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Fiats$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Fiats";
  readonly sourceName: "evm/protocol/libraries/Fiats.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212200fb59467dcd5ae69e63736cd84a368a084f4e5752820161ef0dfd8354b9898f464736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212200fb59467dcd5ae69e63736cd84a368a084f4e5752820161ef0dfd8354b9898f464736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Fiats.sol";
  readonly buildInfoId: "solc-0_8_26-802df857b4f0e4d33c22244765cfd6849ccfb299";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Fiats"]: Fiats$Type;
    ["evm/protocol/libraries/Fiats.sol:Fiats"]: Fiats$Type;
  }
}