// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Fiats$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Fiats";
  readonly sourceName: "evm/protocol/libraries/Fiats.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220276e61a7970235463a47a1ee00353214d5003433b28383cb300c25eecb7b860164736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220276e61a7970235463a47a1ee00353214d5003433b28383cb300c25eecb7b860164736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Fiats.sol";
  readonly buildInfoId: "solc-0_8_26-498cf4de8f98e3f32f5701ac44f6820a2f3455d6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Fiats"]: Fiats$Type;
    ["evm/protocol/libraries/Fiats.sol:Fiats"]: Fiats$Type;
  }
}