// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TickMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TickMath";
  readonly sourceName: "evm/protocol/libraries/TickMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212205791ff3cabbe0937190181282e5a85b1646c70a5b2a91fc4e07de849c570f3cc64736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212205791ff3cabbe0937190181282e5a85b1646c70a5b2a91fc4e07de849c570f3cc64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/TickMath.sol";
  readonly buildInfoId: "solc-0_8_26-498cf4de8f98e3f32f5701ac44f6820a2f3455d6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TickMath"]: TickMath$Type;
    ["evm/protocol/libraries/TickMath.sol:TickMath"]: TickMath$Type;
  }
}