// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TickMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TickMath";
  readonly sourceName: "evm/protocol/libraries/TickMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122034273c93f6b2e880594ac926ce4d44b7ac1e1f7a0667c619efc8c59cb4ea4d0664736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122034273c93f6b2e880594ac926ce4d44b7ac1e1f7a0667c619efc8c59cb4ea4d0664736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/TickMath.sol";
  readonly buildInfoId: "solc-0_8_26-98d7f34ac90c429598174ff08d948dc55cca2d4b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TickMath"]: TickMath$Type;
    ["evm/protocol/libraries/TickMath.sol:TickMath"]: TickMath$Type;
  }
}