// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Tokens$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Tokens";
  readonly sourceName: "evm/protocol/libraries/Tokens.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212201493bdea33f7ad284f310d62bd5588dc226d271752e3686be41a5682d9de58e764736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212201493bdea33f7ad284f310d62bd5588dc226d271752e3686be41a5682d9de58e764736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Tokens.sol";
  readonly buildInfoId: "solc-0_8_26-dadc40e98479a2f65a645405c962b3a16d35f502";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Tokens"]: Tokens$Type;
    ["evm/protocol/libraries/Tokens.sol:Tokens"]: Tokens$Type;
  }
}