// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Tokens$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Tokens";
  readonly sourceName: "evm/protocol/libraries/Tokens.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212209b21cb5252ceae9c89e96aa21a8bb70745e34a3f4d1b85244daafd4bd3915b6664736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212209b21cb5252ceae9c89e96aa21a8bb70745e34a3f4d1b85244daafd4bd3915b6664736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Tokens.sol";
  readonly buildInfoId: "solc-0_8_26-498cf4de8f98e3f32f5701ac44f6820a2f3455d6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Tokens"]: Tokens$Type;
    ["evm/protocol/libraries/Tokens.sol:Tokens"]: Tokens$Type;
  }
}