import { render, screen, waitFor } from '@testing-library/react'
import UserDeals from '@/pages/Me/UserDeals'
import { MemoryRouter } from 'react-router-dom'
import { useAccount } from 'wagmi'
import { useContract } from '@/hooks/useContract'

// Mock wagmi
vi.mock('wagmi', () => ({
  useAccount: vi.fn(),
}))

// Mock hooks
vi.mock('@/hooks/useContract', () => ({
  useContract: vi.fn(),
}))

// Mock models
vi.mock('@/model/Deal.js', () => {
  return {
    default: class Deal {
      // mocked constructor
      constructor(c) {
        this.contract = c
      }
      fetch() {
        return Promise.resolve(this)
      }
    },
  }
})
vi.mock('@/model/Offer.js', () => {
  return {
    default: {
      fetch: () => Promise.resolve({ token: '0xToken', fiat: 'USD', method: 'Bank' }),
    },
  }
})

describe('UserDeals', () => {
  const mockMarket = {
    queryFilter: vi.fn(),
    filters: { DealCreated: vi.fn() },
    runner: { getBlock: vi.fn() },
    token: vi.fn(),
  }
  const mockDealContract = { attach: vi.fn((addr) => ({ target: addr })) }
  const mockOfferContract = { attach: vi.fn() }

  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(useContract).mockReturnValue({
      Market: mockMarket,
      Deal: mockDealContract,
      Offer: mockOfferContract,
    } as any)
  })

  it('renders empty state when no deals found', async () => {
    vi.mocked(useAccount).mockReturnValue({ address: '0xAlice' } as any)
    mockMarket.queryFilter.mockResolvedValue([])

    render(
      <MemoryRouter>
        <UserDeals />
      </MemoryRouter>
    )

    await waitFor(() => {
      const noData = screen.getAllByText(/No data/i)
      expect(noData.length).toBeGreaterThan(0)
    })
  })

  it('renders list of deals', async () => {
    vi.mocked(useAccount).mockReturnValue({ address: '0xAlice' } as any)

    // Mock Logs
    const log1 = { args: [null, null, null, '0xDeal1'], blockHash: '0xBlock' }
    mockMarket.queryFilter.mockResolvedValue([log1])

    // Mock Block
    mockMarket.runner.getBlock.mockResolvedValue({ timestamp: 1000 })

    // Mock Token
    mockMarket.token.mockResolvedValue({ decimals: 18 })

    render(
      <MemoryRouter>
        <UserDeals />
      </MemoryRouter>
    )

    await waitFor(() => {
      // Check for State Log (Initiated is default state 0 if mocked Deal defaults correctly)
      // Wait, we need to ensure Deal instance has properties.
      // In the mocked model logic, `fetch` returns `this`.
      // UserDeals assigns properties to it.

      // We check for some UI element generated by DealItem
      const items = screen.getAllByText(/Created:/)
      expect(items.length).toBeGreaterThan(0)
      expect(items[0]).toBeDefined()
    })
  })
})
