// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Offers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Offers";
  readonly sourceName: "evm/protocol/libraries/Offers.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212209615893d1af4a3b8070259c930608e74ca8f00121607caa2b7353cfcd0a7bdd564736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212209615893d1af4a3b8070259c930608e74ca8f00121607caa2b7353cfcd0a7bdd564736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Offers.sol";
  readonly buildInfoId: "solc-0_8_26-498cf4de8f98e3f32f5701ac44f6820a2f3455d6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Offers"]: Offers$Type;
    ["evm/protocol/libraries/Offers.sol:Offers"]: Offers$Type;
  }
}