// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Offers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Offers";
  readonly sourceName: "evm/protocol/libraries/Offers.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220418889e6fc7db1b3dd25e1318bbb10c83a5a1d7e7d96a4d4d4f8e01b31682af564736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220418889e6fc7db1b3dd25e1318bbb10c83a5a1d7e7d96a4d4d4f8e01b31682af564736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Offers.sol";
  readonly buildInfoId: "solc-0_8_26-2b6cca9693c5e143c47dab423d3080321cfcb067";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Offers"]: Offers$Type;
    ["evm/protocol/libraries/Offers.sol:Offers"]: Offers$Type;
  }
}