/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../common.js"
  import type { MockUniswapV3Factory, MockUniswapV3FactoryInterface } from "../../../../../evm/protocol/mocks/MockUniswapV3Factory.sol/MockUniswapV3Factory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenA",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "tokenB",
        "type": "address"
      },
      {
        "internalType": "uint24",
        "name": "fee",
        "type": "uint24"
      }
    ],
    "name": "getPool",
    "outputs": [
      {
        "internalType": "address",
        "name": "pool",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenA",
        "type": "address"
      }
    ],
    "name": "pools",
    "outputs": [
      {
        "internalType": "address",
        "name": "pool",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenA",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "pool",
        "type": "address"
      }
    ],
    "name": "setPool",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346015576101a1908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081631698ee82146100eb575080634e847fc7146100815763a4063dbc1461003d575f80fd5b3461007d57602036600319011261007d576001600160a01b0361005e61013f565b165f525f60205260206001600160a01b0360405f205416604051908152f35b5f80fd5b3461007d57604036600319011261007d5761009a61013f565b6001600160a01b036100aa610155565b91165f525f6020526001600160a01b0360405f2091167fffffffffffffffffffffffff00000000000000000000000000000000000000008254161790555f80f35b3461007d57606036600319011261007d5761010461013f565b9061010d610155565b5060443562ffffff81160361007d576001600160a01b03602092165f525f82526001600160a01b0360405f2054168152f35b600435906001600160a01b038216820361007d57565b602435906001600160a01b038216820361007d5756fea26469706673582212206cd7eb91dafecd753dc43efb4293a08b07f6afc511de4a822e2d53c149c5bc2864736f6c634300081a0033";

  
      type MockUniswapV3FactoryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockUniswapV3FactoryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockUniswapV3Factory__factory extends ContractFactory {
    
      constructor(...args: MockUniswapV3FactoryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockUniswapV3Factory & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockUniswapV3Factory__factory {
      return super.connect(runner) as MockUniswapV3Factory__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockUniswapV3FactoryInterface {
      return new Interface(_abi) as MockUniswapV3FactoryInterface;
    }
    
    override attach(address: string | Addressable): MockUniswapV3Factory {
      return super.attach(address) as MockUniswapV3Factory;
    }
  static connect(address: string, runner?: ContractRunner | null): MockUniswapV3Factory {
      return new Contract(address, _abi, runner) as unknown as MockUniswapV3Factory;
    }
  }

  
  