/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../common.js"
  import type { PoolETH, PoolETHInterface } from "../../../../../evm/protocol/mocks/MockUniswapV3Factory.sol/PoolETH.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint32[]",
        "name": "secondsAgos",
        "type": "uint32[]"
      }
    ],
    "name": "observe",
    "outputs": [
      {
        "internalType": "int56[]",
        "name": "tickCumulatives",
        "type": "int56[]"
      },
      {
        "internalType": "uint160[]",
        "name": "secondsPerLiquidityCumulativeX128s",
        "type": "uint160[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601557610224908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c63883bdbfd14610024575f80fd5b3461017f57602036600319011261017f5760043567ffffffffffffffff811161017f573660238201121561017f5780600401359067ffffffffffffffff821161017f57602490369260051b01011161017f576100806060610183565b600281526020810190604080368437651000b8e904d1196100a0836101bd565b52651000bc64af4d196100b2836101de565b526100bd6060610183565b926002845260208401913683376c0571e46eb6f9cf3fd28a47fbe36100e1856101bd565b526c0571e46ebef0f3697f3f92a7296100f9856101de565b52604051938493604085019060408652518091526060850192905f5b818110610163575050506020908483038286015251918281520191905f5b818110610141575050500390f35b82516001600160a01b0316845285945060209384019390920191600101610133565b825160060b855287965060209485019490920191600101610115565b5f80fd5b6040519190601f01601f1916820167ffffffffffffffff8111838210176101a957604052565b634e487b7160e01b5f52604160045260245ffd5b8051156101ca5760200190565b634e487b7160e01b5f52603260045260245ffd5b8051600110156101ca576040019056fea2646970667358221220df4fd2ac07842fd8560b335a5ff140a79bcdccae65a766b3eb309f98dc2f239864736f6c634300081a0033";

  
      type PoolETHConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PoolETHConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class PoolETH__factory extends ContractFactory {
    
      constructor(...args: PoolETHConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<PoolETH & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): PoolETH__factory {
      return super.connect(runner) as PoolETH__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PoolETHInterface {
      return new Interface(_abi) as PoolETHInterface;
    }
    
    override attach(address: string | Addressable): PoolETH {
      return super.attach(address) as PoolETH;
    }
  static connect(address: string, runner?: ContractRunner | null): PoolETH {
      return new Contract(address, _abi, runner) as unknown as PoolETH;
    }
  }

  
  