/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../common.js"
  import type { PoolBTC, PoolBTCInterface } from "../../../../../evm/protocol/mocks/MockUniswapV3Factory.sol/PoolBTC.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint32[]",
        "name": "secondsAgos",
        "type": "uint32[]"
      }
    ],
    "name": "observe",
    "outputs": [
      {
        "internalType": "int56[]",
        "name": "tickCumulatives",
        "type": "int56[]"
      },
      {
        "internalType": "uint160[]",
        "name": "secondsPerLiquidityCumulativeX128s",
        "type": "uint160[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460155761023f908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c63883bdbfd14610024575f80fd5b3461019a57602036600319011261019a5760043567ffffffffffffffff811161019a573660238201121561019a5780600401359067ffffffffffffffff821161019a57602490369260051b01011161019a57610080606061019e565b600281526020810190604080368437650838cfdf627a196100a0836101d8565b52650838ceb9a234196100b2836101f9565b526100bd606061019e565b926002845260208401913683377303cf27481a1877584745748f8f0f49a2343e45a56100e8856101d8565b527303cf27481a1877596c7a93e7009ad47da76a91da610107856101f9565b52604051938493604085019060408652518091526060850192905f5b81811061017e575050506020908483038286015251918281520191905f5b81811061014f575050500390f35b825173ffffffffffffffffffffffffffffffffffffffff16845285945060209384019390920191600101610141565b825160060b855287965060209485019490920191600101610123565b5f80fd5b6040519190601f01601f1916820167ffffffffffffffff8111838210176101c457604052565b634e487b7160e01b5f52604160045260245ffd5b8051156101e55760200190565b634e487b7160e01b5f52603260045260245ffd5b8051600110156101e5576040019056fea264697066735822122081b415b8a3b2fbb13ef70d06a1485a3fc0b21d3f26fb7cda2a9c80e458fdd76464736f6c634300081a0033";

  
      type PoolBTCConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: PoolBTCConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class PoolBTC__factory extends ContractFactory {
    
      constructor(...args: PoolBTCConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<PoolBTC & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): PoolBTC__factory {
      return super.connect(runner) as PoolBTC__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): PoolBTCInterface {
      return new Interface(_abi) as PoolBTCInterface;
    }
    
    override attach(address: string | Addressable): PoolBTC {
      return super.attach(address) as PoolBTC;
    }
  static connect(address: string, runner?: ContractRunner | null): PoolBTC {
      return new Contract(address, _abi, runner) as unknown as PoolBTC;
    }
  }

  
  