// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FullMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FullMath";
  readonly sourceName: "evm/protocol/libraries/FullMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212207c6eced9d5822fd3d84b47631d636740ccbb218f6dbfb82b2c51f234dc6929e964736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212207c6eced9d5822fd3d84b47631d636740ccbb218f6dbfb82b2c51f234dc6929e964736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/FullMath.sol";
  readonly buildInfoId: "solc-0_8_26-96e639af8cdfc0e6d2c310f7ace3d1f55e5943fa";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FullMath"]: FullMath$Type;
    ["evm/protocol/libraries/FullMath.sol:FullMath"]: FullMath$Type;
  }
}