// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FullMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FullMath";
  readonly sourceName: "evm/protocol/libraries/FullMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212209706d8dc2dc09c701291a19b548414d8d7cbeb23c8e8f794fb21ad7e9fea963664736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212209706d8dc2dc09c701291a19b548414d8d7cbeb23c8e8f794fb21ad7e9fea963664736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/FullMath.sol";
  readonly buildInfoId: "solc-0_8_26-1737df5eb94312cf2458bb21908a35a4528ad07d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FullMath"]: FullMath$Type;
    ["evm/protocol/libraries/FullMath.sol:FullMath"]: FullMath$Type;
  }
}