// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Methods$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Methods";
  readonly sourceName: "evm/protocol/libraries/Methods.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220cd4e2cccba11dba4700a5162913c740ac6f3fe02f324f3c96f27f73637d6900064736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220cd4e2cccba11dba4700a5162913c740ac6f3fe02f324f3c96f27f73637d6900064736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Methods.sol";
  readonly buildInfoId: "solc-0_8_26-1737df5eb94312cf2458bb21908a35a4528ad07d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Methods"]: Methods$Type;
    ["evm/protocol/libraries/Methods.sol:Methods"]: Methods$Type;
  }
}