// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Methods$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Methods";
  readonly sourceName: "evm/protocol/libraries/Methods.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d13027b1139cedf4d78d8ec8a0a33a5e1af189865c795e90167b31f0ad1441bd64736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220d13027b1139cedf4d78d8ec8a0a33a5e1af189865c795e90167b31f0ad1441bd64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Methods.sol";
  readonly buildInfoId: "solc-0_8_26-f3736ee976c297a6b3d8993eed20057d531c10ae";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Methods"]: Methods$Type;
    ["evm/protocol/libraries/Methods.sol:Methods"]: Methods$Type;
  }
}