// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Deals$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Deals";
  readonly sourceName: "evm/protocol/libraries/Deals.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212206e22a19f05491787688046cdf1ce3f25d04d848b3bcb9b694dd41af7f354632164736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212206e22a19f05491787688046cdf1ce3f25d04d848b3bcb9b694dd41af7f354632164736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Deals.sol";
  readonly buildInfoId: "solc-0_8_26-4ddf1cd2ca392b5d8ae7e1f969cafb79095bd4ac";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Deals"]: Deals$Type;
    ["evm/protocol/libraries/Deals.sol:Deals"]: Deals$Type;
  }
}