// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Deals$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Deals";
  readonly sourceName: "evm/protocol/libraries/Deals.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220443574741c08f0fc19e7c1cc81aa761afaa2e093bc89510aa891fbf853ddd95c64736f6c634300081a0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220443574741c08f0fc19e7c1cc81aa761afaa2e093bc89510aa891fbf853ddd95c64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/evm/protocol/libraries/Deals.sol";
  readonly buildInfoId: "solc-0_8_26-7fb96dc4d6ad55c28d032b65c9558ca60a213082";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Deals"]: Deals$Type;
    ["evm/protocol/libraries/Deals.sol:Deals"]: Deals$Type;
  }
}